---
# - hosts: instances
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: git-pull-source-repository

- hosts: crawler
  gather_facts: true
  vars_files:
    - host_vars/config.yaml
#    - host_vars/deploy.yaml
  roles:
    - role: deploy-crawler

- hosts: backend
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: git-pull-source-repository
    - role: deploy-backend-server

#- hosts: database
#  vars_files:
#    - host_vars/config.yaml
#  gather_facts: true
#  roles:
#    - role: deploy-couchdb
